scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporters"
    static_configs:
      - targets:
          - "192.168.122.230:9100"
          - "192.168.122.240:9100"

